// src/components/game-preact.tsx
import { useEffect } from "preact/hooks";
import { isClient } from "shared/is/env";
import game from "./game";
import "./game-preact.css";

function cx(...args: unknown[]) {
  return args
    .flat()
    .filter((x) => typeof x === "string")
    .join(" ")
    .trim();
}

export function GamePreact() {
  useEffect(() => {
    if (isClient) game.init();
  }, []);

  const isActiveCell = (x: number, y: number) => {
    return (
      game.Board.activeCoords.value?.x === x &&
      game.Board.activeCoords.value?.y === y
    );
  };

  return (
    <div>
      <h1>Score: {game.Score.score}</h1>

      <ul class="next-balls">
        {game.NextBalls.balls.value.map((ball) => (
          <li class={cx("ball", ball?.color ?? "invisible")} />
        ))}
      </ul>

      <button onClick={() => game.start()}>restart</button>
      <button onClick={() => game.nextTurn()}>nextTurn</button>

      <p>isShaking: {String(game.isShaking)}</p>
      <p>isAnimating: {String(game.isAnimating)}</p>

      <table class={cx("grid", game.isShaking.value && "shake")}>
        {game.Board.grid.value.map((row, y) => (
          <tr>
            {row.map((cell, x) => (
              <td
                onClick={() => game.cellClick({ x, y })}
                class={cx(isActiveCell(x, y) && "active")}
              >
                <div
                  class={cx(
                    "ball",
                    cell?.color ?? "invisible",
                    cell?.isMoving && "moving"
                  )}
                />
              </td>
            ))}
          </tr>
        ))}
      </table>
    </div>
  );
}

// src/components/game.svelte
<script lang="ts">
  import { isClient } from "shared/is/env";
  import { fade } from "svelte/transition";
  import game from "./game";

  if (isClient) game.init();

  const fakeBalls = ["transparent", "transparent", "transparent"];
</script>

<h1>Score: {$game.score.value}</h1>

<ul class="next-balls">
  {#if $game.nextBalls.value.length === 0}
    {#each fakeBalls as color}
      <li in:fade out:fade class="ball {color}" />
    {/each}
  {:else}
    {#each $game.nextBalls.value as ball}
      <li in:fade out:fade class="ball {ball.color}" />
    {/each}
  {/if}
</ul>

<button on:click={() => game.start()}>restart</button>
<button on:click={() => game.nextTurn()}>nextTurn</button>

<table class="grid">
  {#each $game.board.grid as row, y}
    <tr>
      {#each row as cell, x}
        <td
          on:click={() => game.cellClick({ x, y })}
          class:active={$game.board.activeCoords?.x === x &&
            $game.board.activeCoords?.y === y}
        >
          {#if cell}
            <div class="ball {cell?.color}" in:fade out:fade />
          {:else}
            <div />
          {/if}
        </td>
      {/each}
    </tr>
  {/each}
</table>

<style scoped>
  .grid {
    border-spacing: 4px;
    border-collapse: separate;
  }

  .grid td {
    min-width: 64px;
    height: 64px;
    text-align: center;
    line-height: 64px;
    background: rgba(255, 255, 255, 0.1);
    border-radius: 4px;
  }

  .grid td.active {
    background: rgba(255, 255, 255, 0.2);
  }

  .next-balls {
    display: flex;
    list-style-type: none;
  }

  .ball {
    border-radius: 50%;
    width: 48px;
    height: 48px;
    margin: 8px;
    position: static;
    box-shadow: 2px 2px 6px 0 rgba(0, 0, 0, 0.1),
      inset -8px -8px 16px 0 rgba(0, 0, 0, 0.25);
  }

  .ball.transparent {
    background: white;
    opacity: 0.2;
  }

  .ball.aqua {
    background: #06b6d4;
  }
  .ball.blue {
    background: #3b82f6;
  }
  .ball.green {
    background: #22c55e;
  }
  .ball.pink {
    background: #ec4899;
  }
  .ball.red {
    background: #ef4444;
  }
  .ball.violet {
    background: #8b5cf6;
  }
  .ball.yellow {
    background: #eab308;
  }
</style>
